"""empty message

Revision ID: 3494af4986e0
Revises: 
Create Date: 2023-04-16 17:08:06.902329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3494af4986e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request',
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('userId', sa.VARCHAR(length=32), nullable=False),
    sa.Column('friendId', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['friendId'], ['user.id'], name='friendrequest_friend_id_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='friendrequest_user_id_fkey')
    )
    # ### end Alembic commands ###
